"""
Setup script for pandasv2 - Advanced Pandas for Web Applications

Installation: pip install -e .
PyPI deployment: twine upload dist/*

Built by Mahesh Makvana
"""

from setuptools import setup, find_packages
import os

# Read long description from README
def read_file(filename):
    path = os.path.join(os.path.dirname(__file__), filename)
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8') as f:
            return f.read()
    return ''

setup(
    name='pandasv2',
    version='2.4.2',
    author='Mahesh Makvana',
    author_email='maheshmakwana527@gmail.com',
    description='pandasv2: pandas drop-in replacement with memory optimization, nested JSON handling, parallel groupby, chunked processing, fast apply, unified apply/map API, safe merge validation, dtype optimization, DataFrame profiling, append compatibility for pandas 3.0, JSON serialization, diff tracking, column validation, streaming export, and seamless FastAPI/Flask/Django integration',
    long_description=read_file('README.md'),
    long_description_content_type='text/markdown',
    url='https://github.com/maheshmakvana/pandasv2',
    project_urls={
        'Source': 'https://github.com/maheshmakvana/pandasv2',
        'Tracker': 'https://github.com/maheshmakvana/pandasv2/issues',
        'Documentation': 'https://github.com/maheshmakvana/pandasv2#readme',
    },
    license='MIT',
    packages=find_packages(),
    python_requires='>=3.8',
    install_requires=[
        'numpy>=1.20.0',
        'pandas>=1.3.0',
    ],
    extras_require={
        'fastapi': ['fastapi>=0.70.0'],
        'flask': ['flask>=2.0.0'],
        'django': ['django>=3.2'],
        'dev': ['pytest>=6.0', 'pytest-cov>=2.12.0'],
    },
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Office/Business',
        'Topic :: Scientific/Engineering :: Information Analysis',
    ],
    keywords=[
        'pandas',
        'pandasv2',
        'pandas2',
        'pandas drop-in',
        'pandas replacement',
        'pandas alternative',
        'pandas memory optimization',
        'reduce pandas memory',
        'pandas memory usage',
        'pandas memory efficient',
        'pandas large dataframe',
        'pandas chunked processing',
        'pandas out of memory',
        'pandas nested json',
        'pandas flatten json',
        'pandas explode nested',
        'pandas json normalize',
        'nested json to dataframe',
        'json serialization pandas',
        'pandas json',
        'dataframe json',
        'pandas to json',
        'int64 not json serializable pandas',
        'object of type int64 is not json serializable',
        'pandas not json serializable',
        'fastapi pandas',
        'flask pandas',
        'django pandas',
        'pandas web api',
        'pandas rest api',
        'pandas fast apply',
        'pandas parallel apply',
        'pandas vectorized apply',
        'pandas apply optimization',
        'pandas apply vs map',
        'pandas unified apply',
        'pandas applymap deprecated',
        'pandas parallel groupby',
        'pandas multiprocessing groupby',
        'pandas groupby parallel',
        'pandas groupby optimization',
        'pandas append removed',
        'pandas append alternative',
        'pandas 3.0 append',
        'pandas append deprecated',
        'dataframe append replacement',
        'pandas dtype optimization',
        'pandas auto categorical',
        'pandas optimize dtypes',
        'pandas downcast integer',
        'pandas downcast float',
        'pandas safe merge',
        'pandas merge validation',
        'pandas cardinality merge',
        'pandas merge check keys',
        'pandas copy on write',
        'pandas chained assignment error',
        'pandas 3.0 migration',
        'pandas 3.0 breaking changes',
        'dataframe pipeline',
        'dataframe diff',
        'dataframe cache',
        'dataframe validation',
        'dataframe profiling',
        'streaming dataframe',
        'data quality',
        'dataframe change detection',
        'pandas profiling',
        'pandas pipeline',
        'pandas validation',
        'pandas caching',
        'data analytics',
        'data science',
        'dataframe',
        'data manipulation',
        'data wrangling',
        'etl',
        'data transformation',
    ],
    include_package_data=True,
    zip_safe=False,
)
